INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '롯데호텔', '서울', '서울시 구로구', 1, 3.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', '광주시', '20', '4.8');

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '동대문라마다호텔', '서울', '동대문구', 6, 2.4);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, 'SUN', '서울', '서울특별시 강남구 논현동 57-13', 10, 4.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '신라호텔(안양)', '안양', '안양시 만안구 경수대로', 3, 3.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '부산호텔', '부산', '부산광역시 강서구 대저2동', 10, 2.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '대구호텔', '대구', '대구광역시 북구 칠성동1가', 6, 2.4);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '청주호텔', '청주', '청주시 서원구 사직동', 2, 3.5);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '단양 익스트림 호텔', '충북', '충북 단양군 단양읍 단양로 896', 10, 1.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '비발디파크 호텔', '강원도', '홍천군 서면 한치골길 262', 2, 2.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '여수 밤바다 호텔', '여수', '전라남도 여수시 종화동', 3, 2.3);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '신라호텔(제주)', '제주', '제주특별자치도 서귀포시 서호동', 2, 2);


INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '더블스위트룸', 1, 120000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '스위트룸', 1, 100000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '글레이즈룸', 1, 80000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '베이글룸', 1, 60000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '테라스가 있는 방',2, 140000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '테라스가 없는 방',2, 100000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '디럭스', 3, 50000, 3);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '프리미엄디럭스', 3, 80000, 5);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '플랙스', 3, 150000, 5);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '태양', 4, 120000, 5);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '싱글룸', 5, 80000, 2);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '더블디럭스', 6, 100000, 6);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '베이직룸', 7, 70000, 2);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '프미미엄룸', 7, 100000, 4);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '해돋이', 8, 150000, 4);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '해질녘', 8, 150000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '싱글', 9, 110000, 2); 

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '더블싱글', 9, 110000, 2);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '퀸', 9, 160000, 4); 

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '하이퍼디럭스',10, 200000, 6);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '오메가디럭스', 10, 30000, 6);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '울트라디럭스', 10, 550000, 4);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '의자', 11, 330000, 4);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '책상', 11, 440000, 4);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '프라이빗', 12, 330000, 6);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '프라이머리', 12, 440000, 8);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '프레지던트', 12, 550000, 10);



INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, '12345', '12345', '정홍주', '010-7708-1908', 'asdf@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, '123', '123', '정다영', '010-7708-1908', 'STEVEN@NAVER.COM', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES(SEQ_BM_MEMBER.NEXTVAL, '1234', '1234', '신종하', '010-3380-7765', 'SMILEJOHN@HANMAIL.NET', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'LEE', '1234', '이상엽', '010-9731-0550', 'sangyoeb@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'admin', '1234', '관리자', '123-456-7890', 'admin@admin.com', 1, 0);



INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-02-29', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-02-29', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-02-29', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-02-29', 0);

INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 1, '2020-03-31', 0);

INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 2, '2020-03-31', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 3, '2020-03-31', 0);

INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 4, '2020-03-31', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 5, '2020-03-31', 0);

INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 6, '2020-03-31', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 7, '2020-03-31', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 8, '2020-03-31', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 9, '2020-03-31', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 10, '2020-03-31', 0);


INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 11, '2020-03-31', 0);



INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-01', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-02', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-03', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-04', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-05', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-06', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-07', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-08', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-09', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-10', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-11', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-12', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-13', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-14', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-15', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-16', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-17', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-18', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-19', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-20', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-21', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-22', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-23', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-24', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-25', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-26', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-27', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-28', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-29', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-30', 0);
INSERT INTO SCHEDULE(SEQ, HOTELSEQ, RESVDATE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, 12, '2020-03-31', 0);