INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '롯데호텔', '서울', '서울시 구로구', 1, 3.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', '광주시', '20', '4.8');

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '동대문라마다호텔', '서울', '동대문구', 6, 2.4);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, 'SUN', '서울', '서울특별시 강남구 논현동 57-13', 10, 4.2);
select * from schedule;
SELECT *
 FROM HOTEL;
 
 
 CREATE TABLE SCHEDULE(
SEQ NUMBER(8) PRIMARY KEY,
HOTELSEQ NUMBER(8) NOT NULL,
RESVDATE VARCHAR2(20) NOT NULL,
USE NUMBER(1)
);

SELECT HOTELSEQ, USE FROM SCHEDULE_TEST;

 UPDATE SCHEDULE_TEST 
 SET USE = 1 
 WHERE RESVDATE BETWEEN '2020-02-01' AND '2020-02-05'
 AND HOTELSEQ = 2

SELECT *
FROM ROOM;

SELECT *
FROM BM_MEMBER;

SELECT *
FROM QNA;

SELECT *
FROM REVIEW;

SELECT *
FROM SCHEDULE;

SELECT *
FROM RESV;

SELECT * FROM RESV;



INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '스위트룸', 1, 100000, 4); 

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '테라스가 있는 방',2, 140000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '디럭스', 3, 50000, 3);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '태양', 4, 120000, 5);




INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'disk123', '123123', '정홍주', '010-7708-1908', 'asdf@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'MYID', 'MYPWD', 'STEVEN', '010-7708-1908', 'STEVEN@NAVER.COM', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES(SEQ_BM_MEMBER.NEXTVAL, 'SISTECT', '1234QWER', '신종하', '010-3380-7765', 'SMILEJOHN@HANMAIL.NET', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'LEE', '1234', '상엽', '010-9731-0550', 'sangyoeb@naver.com', 0, 0);




INSERT INTO RESV(SEQ, HotelSEQ, MEMBERSEQ, ROOMSEQ, CHECKIN, CHECKOUT, RESVDATE, TOTALPRICE, CURRENT_GUEST, CANCEL, REVIEWIS)
VALUES (SEQ_RESV.NEXTVAL, 1, 1, 1, '20200206', '20200210', SYSDATE, 600000, 2, 0, 0); 

INSERT INTO RESV(SEQ, HotelSEQ, MEMBERSEQ, ROOMSEQ, CHECKIN, CHECKOUT, RESVDATE, TOTALPRICE, CANCEL, CURRENT_GUEST, REVIEWIS)
VALUES(SEQ_RESV.NEXTVAL, 2, 2, 2, '20200128', '20200131', SYSDATE, 280000, 1, 2, 0);

INSERT INTO RESV(SEQ, HotelSEQ, MEMBERSEQ, ROOMSEQ, CHECKIN, CHECKOUT, RESVDATE, TOTALPRICE, CANCEL, CURRENT_GUEST, REVIEWIS)
VALUES(SEQ_RESV.NEXTVAL, 3, 3, 3, '20200204', '20200205', SYSDATE, 50000, 0, 2, 0);

INSERT INTO RESV(SEQ, HotelSEQ, MemberSEQ, RoomSEQ, CheckIn, CheckOut, RESVDATE, TOTALPRICE, CANCEL, CURRENT_GUEST, REVIEWIS)
VALUES (SEQ_RESV.NEXTVAL, 4, 4, 4, '20191224', '20191226', SYSDATE, 360000, 0, 3, 0);

INSERT INTO RESV(SEQ, HotelSEQ, MEMBERSEQ, ROOMSEQ, CHECKIN, CHECKOUT, RESVDATE, TOTALPRICE, CURRENT_GUEST, CANCEL, REVIEWIS)
VALUES (SEQ_RESV.NEXTVAL, 1, 1, 1, '20200206', '20200210', SYSDATE, 600000, 2, 0, 0); 

INSERT INTO RESV(SEQ, HotelSEQ, MEMBERSEQ, ROOMSEQ, CHECKIN, CHECKOUT, RESVDATE, TOTALPRICE, CANCEL, CURRENT_GUEST, REVIEWIS)
VALUES(SEQ_RESV.NEXTVAL, 2, 2, 2, '20200128', '20200131', SYSDATE, 280000, 1, 2, 0);

INSERT INTO RESV(SEQ, HotelSEQ, MEMBERSEQ, ROOMSEQ, CHECKIN, CHECKOUT, RESVDATE, TOTALPRICE, CANCEL, CURRENT_GUEST, REVIEWIS)
VALUES(SEQ_RESV.NEXTVAL, 3, 3, 3, '20200204', '20200205', SYSDATE, 50000, 0, 2, 0);

INSERT INTO RESV(SEQ, HotelSEQ, MemberSEQ, RoomSEQ, CheckIn, CheckOut, RESVDATE, TOTALPRICE, CANCEL, CURRENT_GUEST, REVIEWIS)
VALUES (SEQ_RESV.NEXTVAL, 4, 4, 4, '20191224', '20191226', SYSDATE, 360000, 0, 3, 0);





IINSERT INTO REVIEW(SEQ, HOTELSEQ, ROOMSEQ, RESVSEQ, MEMBERSEQ, TITLE, CONTENT, RATING, WRITEDATE, DEL)
VALUES (SEQ_REVIEW.NEXTVAL, 1, 1, 1, 1, '별로에요', '객실도 더럽고 직원도 불친절하고 개별로입니다 비추먹어라 ㅅㄱ', 1.0 , SYSDATE, 0);

INSERT INTO REVIEW(SEQ, HOTELSEQ, ROOMSEQ, RESVSEQ, MEMBERSEQ, TITLE, CONTENT, RATING, WRITEDATE, DEL)
VALUES(SEQ_REVIEW.NEXTVAL, 2, 2, 2, 2, '잘놀고갑니다', 'ㅈㄱㄴ', 4.7, SYSDATE, 0);

INSERT INTO REVIEW(SEQ, HOTELSEQ, ROOMSEQ, RESVSEQ, MEMBERSEQ, TITLE, CONTENT, RATING, WRITEDATE, DEL)
VALUES(SEQ_REVIEW.NEXTVAL, 3, 3, 3, 3, '방왜이럼', '청소상태가 맘에안들어요', 2.1, SYSDATE, 0);

INSERT INTO REVIEW(SEQ, HotelSEQ, RoomSEQ, ResvSEQ, MemberSEQ, TITLE, CONTENT, RATING, WRITEDATE, DEL)
VALUES(SEQ_REVIEW.NEXTVAL, 4, 4, 4, 4, '좋았어요', '행복한 호캉스를 보냈습니다. 시설도 좋고 무엇보다 청결했어요.', 4.5, SYSDATE, 0);

INSERT INTO REVIEW(SEQ, HotelSEQ, RoomSEQ, ResvSEQ, MemberSEQ, TITLE, CONTENT, RATING, WRITEDATE, DEL)
VALUES(SEQ_REVIEW.NEXTVAL, 4, 4, 4, 4, '123', '123', 3, SYSDATE, 0);



INSERT INTO QNA (SEQ, MEMBERSEQ, REF, STEP, DEPTH, TITLE, CONTENT, WRITEDATE, DEL, ReadCount)
VALUES (SEQ_QNA.NEXTVAL, 1, 0, 0, 0, '질문!!!!', '답변!!!!', SYSDATE, 0, 0);

INSERT INTO QNA(SEQ, MEMBERSEQ, REF, STEP, DEPTH, TITLE, CONTENT, WRITEDATE, DEL, ReadCount)
VALUES(SEQ_QNA.NEXTVAL, 2, 0, 0, 0, '결제 문의', '결제는 어떻게 하나요?', SYSDATE, 0, 0);

INSERT INTO QNA(SEQ, MEMBERSEQ, REF, STEP, DEPTH, TITLE, CONTENT, WRITEDATE, DEL, ReadCount)
VALUES(SEQ_QNA.NEXTVAL, 3, 0, 0, 0, '예약하려면 로그인해야하나요', '...', SYSDATE, 0, 0);

INSERT INTO QNA(SEQ, MemberSEQ, REF, STEP, DEPTH, TITLE, CONTENT, WRITEDATE, DEL, ReadCount)
VALUES(SEQ_QNA.NEXTVAL, 4, 0, 0, 0, '문의합니다', '결제가 안됩니다. 확인부탁드려요.', SYSDATE, 0, 0);




INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-01', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-02', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-03', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-04', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-05', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-06', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-07', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-08', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-09', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-10', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-11', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-12', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-13', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-14', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-15', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-16', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-17', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-18', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-19', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-20', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-21', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-22', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-23', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-24', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-25', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-26', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-27', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-28', '동대문라마다호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-29', '동대문라마다호텔', '서울', 0)


INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-01', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-02', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-03', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-04', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-05', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-06', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-07', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-08', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-09', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-10', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-11', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-12', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-13', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-14', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-15', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-16', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-17', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-18', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-19', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-20', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-21', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-22', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-23', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-24', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-25', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-26', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-27', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-28', 'SUN', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-29', 'SUN', '서울', 0)


INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-01', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-02', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-03', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-04', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-05', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-06', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-07', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-08', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-09', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-10', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-11', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-12', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-13', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-14', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-15', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-16', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-17', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-18', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-19', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-20', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-21', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-22', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-23', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-24', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-25', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-26', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-27', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-28', '롯데호텔', '서울', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-29', '롯데호텔', '서울', 0)


INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-01', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-02', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-03', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-04', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-05', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-06', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-07', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-08', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-09', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-10', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-11', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-12', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-13', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-14', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-15', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-16', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-17', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-18', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-19', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-20', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-21', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-22', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-23', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-24', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-25', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-26', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-27', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-28', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)
INSERT INTO SCHEDULE(SEQ, RESVDATE, NAME, PLACE, USE)
VALUES (SEQ_SCHEDULE.NEXTVAL, '2020-02-29', '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', 0)