INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '롯데호텔', '서울', '서울시 구로구', 1, 3.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '빌리지 호텔 파 이스트 호스피탈리티', '전라남도', '광주시', '20', '4.8');

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '동대문라마다호텔', '서울', '동대문구', 6, 2.4);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, 'SUN', '서울', '서울특별시 강남구 논현동 57-13', 10, 4.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '신라호텔(안양)', '안양', '안양시 만안구 경수대로', 3, 3.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '부산호텔', '부산', '부산광역시 강서구 대저2동', 10, 2.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '대구호텔', '대구', '대구광역시 북구 칠성동1가', 6, 2.4);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '청주호텔', '청주', '청주시 서원구 사직동', 2, 3.5);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '단양 익스트림 호텔', '충북', '충북 단양군 단양읍 단양로 896', 10, 1.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '비발디파크 호텔', '강원도', '홍천군 서면 한치골길 262', 2, 2.2);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES(SEQ_HOTEL.NEXTVAL, '여수 밤바다 호텔', '여수', '전라남도 여수시 종화동', 3, 2.3);

INSERT INTO HOTEL(SEQ, NAME, PLACE, ADDR, USE_COUNT, RATING)
VALUES (SEQ_HOTEL.NEXTVAL, '신라호텔(제주)', '제주', '제주특별자치도 서귀포시 서호동', 2, 2);


INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '더블스위트룸', 1, 120000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '스위트룸', 1, 100000, 4);




INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '테라스가 있는 방',2, 140000, 4);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '테라스가 없는 방',2, 100000, 4);





INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '디럭스', 3, 50000, 3);

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '프리미엄디럭스', 3, 80000, 5);



INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '태양', 4, 120000, 5);
INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '목성', 4, 120000, 5);




INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '싱글룸', 5, 80000, 2);
INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '싱글더블룸', 5, 80000, 2);




INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '더블디럭스', 6, 100000, 6);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '트리플디럭스', 6, 100000, 6);


INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '프미미엄룸', 7, 100000, 4);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '베이직룸', 7, 70000, 2);





INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '해돋이', 8, 150000, 4);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '해질녘', 8, 150000, 4);



INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '싱글', 9, 110000, 2); 

INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '더블싱글', 9, 110000, 2);


INSERT INTO ROOM(SEQ, NAME, HOTELSEQ, PRICE, MAX_GUEST)
VALUES(SEQ_ROOM.NEXTVAL, '하이퍼디럭스',10, 200000, 6);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '울트라디럭스', 10, 550000, 4);



INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '의자가 있는방', 11, 330000, 4);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '책상이 있는방', 11, 440000, 4);



INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '프라이빗', 12, 330000, 6);

INSERT INTO ROOM(SEQ, NAME, HotelSEQ, PRICE, MAX_GUEST)
VALUES (SEQ_ROOM.NEXTVAL, '프레지던트', 12, 550000, 10);



INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, '12345', '12345', '정홍주', '010-7708-1908', 'asdf@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, '123', '123', '정다영', '010-7708-1908', 'STEVEN@NAVER.COM', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES(SEQ_BM_MEMBER.NEXTVAL, '1234', '1234', '신종하', '010-3380-7765', 'SMILEJOHN@HANMAIL.NET', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'LEE', '1234', '이상엽', '010-9731-0550', 'sangyoeb@naver.com', 0, 0);

INSERT INTO BM_MEMBER(SEQ, ID, PWD, NAME, PHONENUM, EMAIL, AUTH, DEL)
VALUES (SEQ_BM_MEMBER.NEXTVAL, 'admin', '1234', '관리자', '123-456-7890', 'admin@admin.com', 1, 0);