DROP TABLE Hotel
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_HOTEL;

CREATE SEQUENCE SEQ_HOTEL
INCREMENT BY 1
START WITH 1;

CREATE TABLE HOTEL(
SEQ NUMBER(8) PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
PLACE VARCHAR2(20) NOT NULL,
ADDR VARCHAR2(100) NOT NULL,
USE_COUNT NUMBER(8) NOT NULL,
RATING NUMBER(3,2) NOT NULL
);

-------------------------------------------------

DROP TABLE Room
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_ROOM;

CREATE SEQUENCE SEQ_ROOM
INCREMENT BY 1
START WITH 1;

CREATE TABLE ROOM(
SEQ NUMBER(8) PRIMARY KEY,
NAME VARCHAR2(100) NOT NULL,
HotelSEQ NUMBER(8) NOT NULL,
PRICE NUMBER(10) NOT NULL,
MAX_GUEST NUMBER(2) NOT NULL
);

ALTER TABLE ROOM
ADD CONSTRAINT FK_ROOM_SEQ0 FOREIGN KEY(HotelSEQ)
REFERENCES HOTEL(SEQ);

-------------------------------------------------------

DROP TABLE RESV
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_RESV;

CREATE SEQUENCE SEQ_RESV
INCREMENT BY 1
START WITH 1;

CREATE TABLE RESV(
SEQ NUMBER(8) PRIMARY KEY,
HotelSEQ NUMBER(8) NOT NULL,
MemberSEQ NUMBER(8) NOT NULL,
RoomSEQ NUMBER(8) NOT NULL,
CheckIn VARCHAR2(20) NOT NULL,
CheckOut VARCHAR2(20) NOT NULL,
RESVDATE DATE NOT NULL,
TOTALPRICE NUMBER(8) NOT NULL,
CURRENT_GUEST NUMBER(2) NOT NULL,
CANCEL NUMBER(1) NOT NULL,
REVIEWIS NUMBER(1) NOT NULL
);

ALTER TABLE RESV
ADD CONSTRAINT FK_RESV_SEQ0 FOREIGN KEY(MemberSEQ)
REFERENCES BM_Member(SEQ);

ALTER TABLE RESV
ADD CONSTRAINT FK_RESV_SEQ1 FOREIGN KEY(RoomSEQ)
REFERENCES Room(SEQ);

ALTER TABLE RESV
ADD CONSTRAINT FK_RESV_SEQ2 FOREIGN KEY(HotelSEQ)
REFERENCES HOTEL(SEQ);

-------------------------------------------------------------

DROP TABLE BM_MEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BM_MEMBER;

CREATE SEQUENCE SEQ_BM_MEMBER
INCREMENT BY 1
START WITH 1;

CREATE TABLE BM_MEMBER(
SEQ NUMBER(8) PRIMARY KEY,
ID VARCHAR2(50) NOT NULL,
PWD VARCHAR2(50) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
PHONENUM VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
AUTH NUMBER(1) NOT NULL,
DEL NUMBER(1) NOT NULL
);

----------------------------------------------------------------

DROP TABLE REVIEW
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REVIEW;

CREATE SEQUENCE SEQ_REVIEW
INCREMENT BY 1
START WITH 1;

CREATE TABLE REVIEW(
SEQ NUMBER(8) PRIMARY KEY,
HotelSEQ NUMBER(8) NOT NULL,
RoomSEQ NUMBER(8) NOT NULL,
ResvSEQ NUMBER(8) NOT NULL,
MemberSEQ NUMBER(8) NOT NULL,
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(500) NOT NULL,
RATING NUMBER(3,2) NOT NULL,
WRITEDATE DATE NOT NULL,
DEL NUMBER(1) NOT NULL
);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_SEQ0 FOREIGN KEY(MemberSEQ)
REFERENCES BM_Member(SEQ);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_SEQ1 FOREIGN KEY(HotelSEQ)
REFERENCES Hotel(SEQ);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_SEQ2 FOREIGN KEY(RoomSEQ)
REFERENCES Room(SEQ);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_SEQ3 FOREIGN KEY(RESVSEQ)
REFERENCES RESV(SEQ);

-----------------------------------------------------------

DROP TABLE QNA
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_QNA;

CREATE SEQUENCE SEQ_QNA
INCREMENT BY 1
START WITH 1;

CREATE TABLE QNA(
SEQ NUMBER(8) PRIMARY KEY,
MemberSEQ NUMBER(8) NOT NULL,
REF NUMBER(2) NOT NULL,
STEP NUMBER(2) NOT NULL,
DEPTH NUMBER(2) NOT NULL,
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(1000) NOT NULL,
WRITEDATE DATE NOT NULL,
DEL NUMBER(1) NOT NULL,
ReadCount NUMBER(8) NOT NULL
);

ALTER TABLE QNA
ADD CONSTRAINT FK_QNA_SEQ0 FOREIGN KEY(MemberSEQ)
REFERENCES BM_Member(SEQ);

------------------------------------------------------------

DROP TABLE SCHEDULE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_SCHEDULE;

CREATE SEQUENCE SEQ_SCHEDULE
INCREMENT BY 1
START WITH 1;

CREATE TABLE SCHEDULE(
SEQ NUMBER(8) PRIMARY KEY,
RESVDATE VARCHAR2(20) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
PLACE VARCHAR2(20) NOT NULL,
USE NUMBER(1)
);

------------------------------------------------------------

DROP TABLE IMAGEFILE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_IMAGEFILE;

CREATE SEQUENCE SEQ_IMAGEFILE
INCREMENT BY 1
START WITH 1;

CREATE TABLE IMAGEFILE(
SEQ NUMBER(8) PRIMARY KEY,
FileName VARCHAR2(200) NOT NULL,
FileRealName VARCHAR2(200) NOT NULL,
HotelSEQ NUMBER(8) NOT NULL,
RoomSEQ NUMBER(8) NOT NULL,
MemberSEQ NUMBER(8) NOT NULL,
ReViewSEQ NUMBER(8) NOT NULL
);

ALTER TABLE IMAGEFILE
ADD CONSTRAINT FK_IMAGEFILE_SEQ0 FOREIGN KEY(MemberSEQ)
REFERENCES BM_Member(SEQ);

ALTER TABLE IMAGEFILE
ADD CONSTRAINT FK_IMAGEFILE_SEQ1 FOREIGN KEY(HotelSEQ)
REFERENCES Hotel(SEQ);

ALTER TABLE IMAGEFILE
ADD CONSTRAINT FK_IMAGEFILE_SEQ2 FOREIGN KEY(RoomSEQ)
REFERENCES Room(SEQ);

ALTER TABLE IMAGEFILE
ADD CONSTRAINT FK_IMAGEFILE_SEQ3 FOREIGN KEY(ReViewSEQ)
REFERENCES REVIEW(SEQ);